### ISSUE TITLE
server side signing?

### ISSUE THREAD

**Issue by mwawrusch** [Missing-Tech/transloadit-flutter-sdk#17]
Hi, 
thanks for creating this library. We need to use transloadit in a mobile app so storing the authkey there (or even transmitting it) is not an option. Perhaps add a means to asynchronously obtain the signature from the backend, e.g. a hook that we can use to call our backend.

**Comment by joegrabski** [comment]
You could use a [Firebase Remote Config](https://firebase.flutter.dev/docs/remote-config/overview) to store your keys elsewhere.

**Comment by mwawrusch** [comment]
Thanks for the suggestion but we prefer to keep our attack surfaces low.

**Comment by joegrabski** [comment]
Course, completely understandable since Firebase is a pretty heavyweight package too. Could you provide some more details as to how you could see this being implemented though?

**Comment by mwawrusch** [comment]
Will get that to you in a day or two, thank you

**Comment by joegrabski** [comment]
No worries :) Happy to receive your feedback on this!

**Comment by mwawrusch** [comment]
Hi, so we decided to switch to uploadcare. Thanks for being receptive to my suggestion though, muhc appreacted

**Comment by joegrabski** [comment]
Sorry to hear that Transloadit wasn't a good fit for you! If you could let us know what made you decide against Transloadit that'd be great :)
